name: flutter_zoom_sdk
description: Zoom SDK from ZOOM ported to flutter as plugin with all necessary features and with Null Safety which is implementation by EvilRATT
version: 1.0.1
homepage: https://github.com/evilrat/flutter_zoom_sdk
repository: https://github.com/evilrat/flutter_zoom_sdk
issue_tracker: https://github.com/evilrat/flutter_zoom_sdk/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  zoom_platform_interface: ^1.0.3+3 
  js: ^0.6.3
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  archive: ^3.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.evilratt.flutter_zoom_sdk
        pluginClass: FlutterZoomSdkPlugin
      ios:
        pluginClass: FlutterZoomSdkPlugin
      web:
        pluginClass: ZoomWeb
        fileName: zoom_web.dart